---
title: "Covid_test_visual"
format:
  html:
    theme: journal

execute:
  echo: false #hide code
  error: true #run even if errors occur
---

```{r}
#| message: false
#| echo: false

# Load data
library(tidyverse)
library(gtsummary)
library(here)
library(janitor)
library(Hmisc)
library(summarytools)
library(ggplot2)
library(broom.helpers)
library(cardx)

#Import Data
raw_data <- readRDS(here::here("data/raw/raw_data.rds"))
#Drop unnecessary variables and NA
edited <- raw_data |>
										select(c(subject_id, age, clinic_name,
																			gender, test_id, result, drive_thru_ind,
																			col_rec_tat, rec_ver_tat)) |>
   na.omit() |>
	
#Label data
		mutate(drive_thru_ind = factor(drive_thru_ind,
																	 levels = c(0,1),
																	 labels = c("No", "Yes")))

label(edited$col_rec_tat) <- "Time (hours) between collection and lab received"
label(edited$rec_ver_tat) <- "Time (hours) between received and test verification"


```
## Table 1 - Summary Statistics
The median and IQR for age is `r inline_text(table1, variable = "age")` years

```{r}
#Load table
#| echo: false
table1 <- tbl_summary(
	edited,
	by = gender,
	include = c(age, result, drive_thru_ind, col_rec_tat,
							rec_ver_tat)) |>
	add_overall(last = TRUE)

summary(edited$age)
table1
```
## Regression Results

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
1 + 1
```

## Figure

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
